# Site settings
title: "Kornholt’s Blog"
email: kornholtblog@outlook.com
description: "My personal wiki-like site"
baseurl: ""
url: "http://kornholt.com"
# Build settings
permalink: '/:year/:month/:title/'
paginate: 5
plugins: [jekyll-paginate]

sass: 
    sass_dir: assets/css
    
navigation:
- title: Home
  url: /
- title: Archive
  url: /archive/
- title: About Me
  url: /about/

exclude: [.git, .gitignore, Gemfile, Gemfile.lock, package.json, Gruntfile.js, node_modules, .DS_Store, .scss-lint.yml]

#Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'http://jokorn.github.io'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_sass
    - 404.html
    - about.md
    - archive.md
    - contact.md
    - /css
    - /images
    - s3_website.yml
    - upload.sh
  metadata:
    _posts:
      - name: "title"
        field:
            element: "text"
            label: "Title"
            placeholder: "Add the post title"
      - name: "description"
        field:
            element: "text"
            label: "Description"
            placeholder: "Add a short description of the post"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Add tags, i.e. [Matlab, fMRI]"
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
          placeholder: "Write a small excerpt (or copy paste the beginning of the post)."
      - name: "image"
        field:
          element: "text"
          label: "Image URL"
          placeholder: "Add the filename of the main image, eg. fun-no-cat.jpg."
        
              
